# Generated by Django 4.1.2 on 2022-10-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
