# Generated by Django 4.1.2 on 2022-10-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
